openapi: 3.0.1
info:
  title: Fractal Market Analyzer
  description: API for analyzing market data using recursive fractal methods.
  version: "1.0.0"

servers:
  - url: https://market-analyzer-vgqs.onrender.com

paths:
  /:
    get:
      summary: Root check
      operationId: rootCheck
      responses:
        "200":
          description: Health check
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from Fractal Market Analyzer (Flask)!

  /analyze:
    post:
      summary: Run market analysis
      operationId: runAnalysis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ticker:
                  type: string
                  example: AAPL
                start_date:
                  type: string
                  format: date
                  example: "2024-01-01"
                end_date:
                  type: string
                  format: date
                  example: "2024-01-31"
      responses:
        "200":
          description: Analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  result:
                    type: object
                    description: The computed market analysis
        "400":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string

