openapi: 3.0.1
info:
  title: Fractal Market Analyzer API
  version: "1.0.0"
  description: API for analyzing financial markets using FAA (Fractal/Field-Aware Analytics).
servers:
  - url: https://market-analyzer-vgqs.onrender.com
paths:
  /:
    get:
      operationId: rootCheck
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello from Fractal Market Analyzer (Flask)!
  /analyze:
    post:
      operationId: runAnalysis
      summary: Run FAA analysis over a tabular payload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [table]
              properties:
                table:
                  type: array
                  description: List of rows with at least {date, firm, sector, numeric features}
                  items:
                    type: object
                feature_cols:
                  type: array
                  items: { type: string }
      responses:
        "200":
          description: FAA results
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  result:
                    type: object
                    properties:
                      last_date: { type: string }
                      coherence:
                        type: object
                        additionalProperties: { type: number }
                      velocity:
                        type: object
                        additionalProperties: { type: number }
                      oom:
                        type: object
                        additionalProperties: { type: number }
                      composite:
                        type: object
                        additionalProperties: { type: number }
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: error }
                  message: { type: string }

